//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public decimal arc_id { get; set; }
        public string arc_emisor { get; set; }
        public Nullable<decimal> arc_dte_folio { get; set; }
        public Nullable<decimal> arc_dte_tipo { get; set; }
        public string arc_tipo { get; set; }
        public string arc_nombre { get; set; }
        public string arc_path { get; set; }
        public Nullable<int> arc_dte_id { get; set; }
    }
}
