//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class Dte
    {
        [Key] //HINT: se añade esta linea para que reconozca cual es la key del schema
        public int dte_id { get; set; }
        public decimal dte_tipo_dte { get; set; }
        public decimal dte_folio { get; set; }
        public string dte_emisor { get; set; }
        public string dte_receptor { get; set; }
        public string dte_emisor_razonsocial { get; set; }
        public string dte_receptor_razonsocial { get; set; }
        public Nullable<System.DateTime> dte_fecha_emision { get; set; }
        public Nullable<System.DateTime> dte_fecha_recepcion { get; set; }
        public Nullable<double> dte_monto_total { get; set; }
        public string dte_sii_estado { get; set; }
        public string dte_sii_estado_desc { get; set; }
        public string dte_tipo_distribucion { get; set; }
        public string dte_acuse { get; set; }
        public string dte_estado_comercial { get; set; }
        public string dte_ws_descargado { get; set; }
        public Nullable<int> dte_resp_cliente_cod { get; set; }
        public string dte_resp_cliente_desc { get; set; }
        public Nullable<int> dte_distribucion_cod { get; set; }
        public string dte_distribucion_desc { get; set; }
        public Nullable<int> dte_comercial_cod { get; set; }
        public string dte_comercial_desc { get; set; }
        public Nullable<int> dte_acuse_cod { get; set; }
        public string dte_acuse_est { get; set; }
        public string dte_url_custodia { get; set; }
        public string dte_tipo_ingreso { get; set; }
        public Nullable<System.DateTime> dte_fch_venc { get; set; }
        public string dte_vlr_codigo { get; set; }
        public Nullable<double> dte_mnt_neto { get; set; }
        public Nullable<double> dte_mnt_exe { get; set; }
        public Nullable<double> dte_tasa_iva { get; set; }
        public Nullable<double> dte_iva { get; set; }
        public Nullable<double> dte_saldo_anterior { get; set; }
        public Nullable<double> dte_vlr_pagar { get; set; }
    }
}
